api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.get_rountes_view),
    path('rooms/', views.get_rooms_views),
    path('rooms/<int:pk>', views.get_room_detail_views),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('topics/', views.topics_page_view, name='topics'),
    path('activity/', views.activity_paga_view, name='activity'),
]

disroom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('room/', include('room.urls')),
    path('account/', include('account.urls')),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/models.py
from django.db import models
from account.models import User


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated_at', '-created_at']

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.body[0:50]

core/views.py
from django.shortcuts import render
from room.models import Room,Topic, Message
from django.db.models import Q

# Create your views here.
def home_view(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))
    topics = Topic.objects.all()[0:5]
    room_count = rooms.count()
    context = {'rooms': rooms, 'room_count': room_count, 'topics': topics, 'room_messages': room_messages}
    return render(request, 'core/home.html', context)

def topics_page_view(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    context = {'topics' : topics}
    return render(request, 'core/mobile_topics.html', context)

def activity_paga_view(request):
    room_messages = Message.objects.all()
    context = {'room_messages': room_messages}
    return render(request, 'core/mobile_activity.html', context)

core/templates/core/activity_component.html
<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>
    {% for message in room_messages %}
    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
        <a href="{% url 'user_profile' message.user.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="{{message.user.avatar.url}}" />
          </div>
          <p>
            @{{message.user}}
            <span>{{message.created_at|timesince}} days ago</span>
          </p>
        </a>
        {% if request.user == message.user %}
        <div class="roomListRoom__actions">
          <a href="{% url 'delete_message' message.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
              ></path>
            </svg>
          </a>
        </div>
        {% endif %}
      </div>
      <div class="activities__boxContent">
        <p>replied to post “<a href="{% url 'room_detail' message.room.id %}">{{message.room}}</a>”</p>
        <div class="activities__boxRoomContent">
            {{message.body}}....
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

core/templates/core/feed_component.html
{% for room in rooms %}
<div class="roomListRoom">
  <div class="roomListRoom__header">
    <a href="{% url 'user_profile' room.host.id %}" class="roomListRoom__author">
      <div class="avatar avatar--small">
        <img src="{{room.host.avatar.url}}" />
      </div>
      <span>@{{room.host.username}}</span>
    </a>
    <div class="roomListRoom__actions">
      <span>{{room.created_at|timesince}} ago</span>
    </div>
  </div>
  <div class="roomListRoom__content">
    <a href="{% url 'room_detail' room.id %}">{{room.name}}</a>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur ducimus harum dolorem, obcaecati
      mollitia omnis quasi aut consequuntur enim itaque labore.
    </p>
  </div>
  <div class="roomListRoom__meta">
    <a href="{% url 'room_detail' room.id %}" class="roomListRoom__joined">
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>user-group</title>
        <path
          d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
        ></path>
        <path
          d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
        ></path>
        <path
          d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
        ></path>
        <path
          d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
        ></path>
      </svg>
      {{room.participants.all.count}} Joined
    </a>
    <p class="roomListRoom__topic">{{room.topic.name}}</p>
  </div>
</div>
{% endfor %}

core/templates/core/home.html
{% extends 'core/main.html' %}

{% block content %}
    <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
        {% include 'core/topics_component.html' %}
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search" action="{% url 'home' %}" method="GET">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                  d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q"  placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{room_count}} Rooms available</p>
            </div>
            <a class="btn btn--main" href="{% url 'create_room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>
          {% include 'core/feed_component.html' %}
        </div>
        <!-- Room List End -->
        
        <!-- Activities Start -->
        {% include 'core/activity_component.html' %}
        <!-- Activities End -->
      </div>
    </main>
{% endblock %}

core/templates/core/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UT F-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>DisRoom - Find study partners around the world!</title>
  </head>

  <body>
    {% include 'core/navbar.html' %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %}
    
    {% endblock %}
    <script src="{% static 'js/script.js'%}"></script>
  </body>
</html>

core/templates/core/mobile_activity.html
{% extends 'core/main.html' %}

{% block content %}
<main class="layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="index.html">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                ></path>
              </svg>
            </a>
            <h3>Recent Activities</h3>
          </div>
        </div>

        <div class="activities-page layout__body">
            {% for message in room_messages %}
            <div class="activities__box">
              <div class="activities__boxHeader roomListRoom__header">
                <a href="{% url 'user_profile' message.user.id %}" class="roomListRoom__author">
                  <div class="avatar avatar--small">
                    <img src="{{message.user.avatar.url}}" />
                  </div>
                  <p>
                    @{{message.user}}
                    <span>{{message.created_at|timesince}} days ago</span>
                  </p>
                </a>
                {% if request.user == message.user %}
                <div class="roomListRoom__actions">
                  <a href="{% url 'delete_message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </a>
                </div>
                {% endif %}
              </div>
              <div class="activities__boxContent">
                <p>replied to post “<a href="{% url 'room_detail' message.room.id %}">{{message.room}}</a>”</p>
                <div class="activities__boxRoomContent">
                    {{message.body}}....
                </div>
              </div>
            </div>
            {% endfor %}
        </div>
      </div>
    </div>
  </main>
  {% endblock %}

core/templates/core/mobile_topics.html
{% extends 'core/main.html' %}

{% block content %}
<main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{% url 'home'%}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                ></path>
              </svg>
            </a>
            <h3>Browse Topics</h3>
          </div>
        </div>

        <div class="topics-page layout__body">
          <form class="header__search" action="" method="get" >
            <label>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>search</title>
                <path
                  d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                ></path>
              </svg>
              <input name="q"  placeholder="Search for posts" />
            </label>
          </form>

          <ul class="topics__list">
            <li>
              <a href="{% url 'topics' %}" class="active">All <span>{{topics.count}}</span></a>
            </li>
            {% for topic in topics %}
            <li>
                <a href="{% url 'home'%}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.count}}</span></a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

core/templates/core/navbar.html
{% load static %}
<header class="header header--loggedIn">
    <div class="container">
      <a href="{% url 'home' %}" class="header__logo">
        <img src="{% static 'images/logo.svg' %}" />
        <h1>DisRoom</h1>
      </a>
      <form class="header__search" action="{% url 'home' %}" method="GET">
        <label>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>search</title>
            <path
              d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
            ></path>
          </svg>
          <input  type="text" name="q" placeholder="Search for rooms..." />
        </label>
      </form>
      <nav class="header__menu">
  
        <!-- Logged In -->
        {% if request.user.is_authenticated %}
        <div class="header__user">
          <a href="{% url 'user_update' %}">
            <div class="avatar avatar--medium active">
              <img src="{{request.user.avatar.url}}" />
            </div>
            <p>{{request.user}} <span>{{request.user.username}}</span></p>
          </a>
          <button class="dropdown-button">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>chevron-down</title>
              <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
            </svg>
          </button>
        </div>
        {% else %}

        <!-- Not Logged In -->

        <a href="{% url 'user_login'%}">
          <img src="{% static 'images/avatar.svg' %}" />
          <p>Login</p>
        </a> 
        {% endif %}

        <div class="dropdown-menu">
          <a href="{% url 'user_update' %}" class="dropdown-link"
            ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>tools</title>
              <path
                d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z"
              ></path>
            </svg>
            Settings</a
          >
          <a href="{% url 'user_logout' %}" class="dropdown-link"
            ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>sign-out</title>
              <path
                d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z"
              ></path>
              <path
                d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z"
              ></path>
            </svg>
            Logout</a
          >
        </div>
      </nav>
    </div>
  </header>

core/templates/core/topics_component.html
<div class="topics">
    <div class="topics__header">
      <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
      <li>
        <a href="{% url 'home'%}" class="active">All <span>{{topics.count}}</span></a>
      </li>
      {% for topic in topics %}
      <li>
        <a href="{% url 'home'%}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.count}}</span></a>
      </li>
      {% endfor %}
    </ul>
    <a class="btn btn--link" href="{% url 'topics' %}">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a>
  </div>